name: Deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      dotnet-version:
        description: "Specify the .NET version to use"
        required: true
        type: string
      sln-path:
        description: "Specify the path to the .sln file"
        required: true
        type: string
      tf-path:
        description: "Specify Terraform path"
        type: string
      role-arn:
        description: "Splecify Deployment role ARN"
        type: string
      
jobs: 
  build-test:
    name: Build And Test
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - run: dotnet build ${{ inputs.sln-path }}

      - run: dotnet test ${{ inputs.sln-path }}
  
      - run: |
          projects=$(grep -oP '(?<=Project\(").*?(?="\))' ${{ inputs.sln-path }} | sed 's/".*,//')
          
          echo "projects : $projects"

          # Loop through each project and check if it is a web project
          web_project=""
          for project in $projects; do
            echo "current project : $project"
            csproj_file="${project##*=}"
            echo "Current csproj file: $csproj_file"
            if grep -q 'Microsoft.NET.Sdk.Web' "$csproj_file"; then
              web_project="$csproj_file"
              break
            fi
          done

          echo "Web proj: $web_project"


  dev-deploy:
    name: Deploy to Dev Env
    runs-on: ubuntu-latest
    needs: build-test
    environment: Dev

    steps: 
      - run: echo "DEPLOYING THE INFRASTRUCTURE TO DEV"

  test-deploy:
    name: Deploy to Test Env
    runs-on: ubuntu-latest
    needs: dev-deploy
    environment: Test

    steps: 
      - run: echo "DEPLOYING THE INFRASTRUCTURE TO Test"

