name: Deploy
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      dotnet-version:
        description: "Specify the .NET version to use"
        required: true
        type: string
      sln-path:
        description: "Specify the path to the .sln file"
        required: true
        type: string
      tf-path:
        description: "Specify Terraform path"
        required: true
        type: string
      role-name:
        description: "Splecify Deployment role ARN"
        required: true
        type: string
      
jobs: 
  build-test:
    name: Build And Test
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - run: dotnet build ${{ inputs.sln-path }}

      - run: dotnet test ${{ inputs.sln-path }}

      - name: Publish
        run: |
          projects=$(awk -F', ' '/Project/ {gsub(/"/, "", $2); print $2}' ${{ inputs.sln-path }} | sed 's/\\/\//g')

          echo "projects : $projects"

          # Loop through each project and check if it is a web project
          web_project=""
          for project in $projects; do
            echo "current project : $project"
            if grep -q 'Microsoft.NET.Sdk.Web' "${{ github.workspace }}/$project"; then
              web_project=${{ github.workspace }}/$project
              break
            fi
          done

          # Publish the web project if found
          if [ -n "$web_project" ]; then
            echo "Web project found: $web_project"
            dotnet publish "$web_project" -c Release -o ./publish --no-restore --verbosity normal
          else
            echo "No web project found in the solution."
            exit 1
          fi


  dev-deploy:
    name: Deploy to Dev Env
    runs-on: ubuntu-latest
    needs: build-test
    environment: Dev

    steps: 
      - name: Configure AWS Credentials from AWS Account in
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/${{ inputs.role-name }}
          aws-region: us-east-1
          role-session-name: ${{ inputs.role-name }}-deployment

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: tfinit
        working-directory: ${{ inputs.tf-path }}
        run: terraform init

      - name: Terraform Plan
        id: tfplan
        working-directory: ${{ inputs.tf-path }}
        run: terraform plan -var-file="dev.tfvars"

  test-deploy:
    name: Deploy to Test Env
    runs-on: ubuntu-latest
    needs: dev-deploy
    environment: Test

    steps: 
      - run: echo "DEPLOYING THE INFRASTRUCTURE TO Test"

